---
abstract: 'Author tests for POD spelling'
author:
  - 'Caleb Cushing <xenoterracide@gmail.com>'
  - 'Marcel Gruenauer <marcel@cpan.org>'
  - 'Harley Pig <harleypig@gmail.com>'
build_requires:
  English: 0
  File::Find: 0
  File::Temp: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200012, CPAN::Meta::Converter version 2.110930'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-Plugin-Test-PodSpelling
no_index:
  file:
    - perlcritic.rc
requires:
  Dist::Zilla::Plugin::InlineFiles: 0
  Dist::Zilla::Role::TextTemplate: 0
  Moose: 0
  Pod::Wordlist::hanekomu: 0
  Test::Spelling: 0
  perl: 5.008
resources: {}
version: 2.0.0
